# -*- coding: utf-8 -*-
"""train_emotion_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/199XmziauaC-slyvoavjkwTRTQYEXj0F3
"""

import os
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout, BatchNormalization
from tensorflow.keras.optimizers import Adam

# Folder paths
BASE_PATH = os.path.join("data", "fer2013")
TRAIN_PATH = os.path.join(BASE_PATH, "train")
TEST_PATH = os.path.join(BASE_PATH, "test")
MODEL_DIR = "models"
MODEL_FILE = os.path.join(MODEL_DIR, "emotion_model.h5")
LABELS_FILE = os.path.join(MODEL_DIR, "emotion_labels.txt")

# Model parameters
IMG_SIZE = (48, 48)
BATCH_SIZE = 64
EPOCHS = 25


def create_data_generators():
    """Creates training and validation generators with data augmentation."""
    train_gen = ImageDataGenerator(
        rescale=1./255,
        rotation_range=15,
        width_shift_range=0.1,
        height_shift_range=0.1,
        zoom_range=0.1,
        horizontal_flip=True
    )

    val_gen = ImageDataGenerator(rescale=1./255)

    train_data = train_gen.flow_from_directory(
        TRAIN_PATH,
        target_size=IMG_SIZE,
        color_mode='grayscale',
        batch_size=BATCH_SIZE,
        class_mode='categorical'
    )

    val_data = val_gen.flow_from_directory(
        TEST_PATH,
        target_size=IMG_SIZE,
        color_mode='grayscale',
        batch_size=BATCH_SIZE,
        class_mode='categorical'
    )

    return train_data, val_data


def build_cnn_model(num_classes):
    """Builds a simple CNN architecture for emotion classification."""
    model = Sequential([
        Conv2D(64, (3, 3), activation='relu', input_shape=(48, 48, 1)),
        BatchNormalization(),
        MaxPooling2D((2, 2)),
        Dropout(0.25),

        Conv2D(128, (3, 3), activation='relu'),
        BatchNormalization(),
        MaxPooling2D((2, 2)),
        Dropout(0.25),

        Conv2D(256, (3, 3), activation='relu'),
        BatchNormalization(),
        MaxPooling2D((2, 2)),
        Dropout(0.25),

        Flatten(),
        Dense(256, activation='relu'),
        Dropout(0.5),
        Dense(num_classes, activation='softmax')
    ])

    model.compile(
        optimizer=Adam(learning_rate=5e-4),
        loss='categorical_crossentropy',
        metrics=['accuracy']
    )
    return model


def main():
    print("[INFO] Preparing data...")
    train_data, val_data = create_data_generators()
    class_labels = list(train_data.class_indices.keys())
    print(f"[INFO] Classes: {class_labels}")

    print("[INFO] Building model...")
    model = build_cnn_model(len(class_labels))
    model.summary()

    print("[INFO] Training started...")
    history = model.fit(
        train_data,
        validation_data=val_data,
        epochs=EPOCHS
    )

    os.makedirs(MODEL_DIR, exist_ok=True)
    model.save(MODEL_FILE)

    with open(LABELS_FILE, "w") as f:
        f.write("\n".join(class_labels))

    print(f"[INFO] Model saved at {MODEL_FILE}")
    print(f"[INFO] Labels saved at {LABELS_FILE}")


if __name__ == "__main__":
    main()